In [25]:
%pip install transformers sentence-transformers openai
%pip install -U datasets
%pip install evaluate accelerate

Requirement already satisfied: transformers in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (5.8.0)
Requirement already satisfied: sentence-transformers in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (5.4.1)
Requirement already satisfied: openai in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (2.36.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (1.14.0)
Requirement already satisfied: numpy>=1.17 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: torch>=1.11.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: scikit-learn>=0.22.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from openai) (2.13.4)
Requirement already satisfied: sniffio in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from openai) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: joblib>=1.3.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)

[notice] A new release of pip is available: 26.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: datasets in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (4.8.5)
Requirement already satisfied: filelock in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (2.4.4)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (1.14.0)
Requirement already satisfied: packaging in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer>=0.20.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: click>=8.2.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: evaluate in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (0.4.6)
Requirement already satisfied: accelerate in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (1.13.0)
Requirement already satisfied: datasets>=2.0.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (2.4.4)
Requirement already satisfied: dill in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (3.0.2)
Requirement already satisfied: requests>=2.19.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (2.33.1)
Requirement already satisfied: tqdm>=4.62.1 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (3.7.0)
Requirement already satisfied: multiprocess in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2026.2.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (1.14.0)
Requirement already satisfied: packaging in /Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages (from evaluate) (26.2)

In [26]:
from datasets import load_dataset

data = load_dataset("rotten_tomatoes")
data

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 8530
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
})

In [27]:
data["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 8530
})

In [28]:
from transformers import pipeline

# Path to our HF model
model_path = "cardiffnlp/twitter-roberta-base-sentiment-latest"

# Load model into pipeline
pipe = pipeline(
    task="text-classification",
    model=model_path,
    tokenizer=model_path,
    top_k=None,
    device="mps",
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 42584.99it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 42584.99it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [29]:
import numpy as np
from tqdm import tqdm
from transformers.pipelines.pt_utils import KeyDataset

# Run inference. top_k=None returns a list of all label scores per input,
# sorted by score, so look them up by label name (not index).
y_pred = []
for output in tqdm(pipe(KeyDataset(data["test"], "text")), total=len(data["test"])):
    scores = {item["label"]: item["score"] for item in output}
    assignment = np.argmax([scores["negative"], scores["positive"]])
    y_pred.append(assignment)

100%|██████████| 1066/1066 [00:15<00:00, 68.59it/s]

In [30]:
from sklearn.metrics import classification_report,confusion_matrix

def evaluate_performance(y_true, y_pred):
    """Create and print the classification report"""
    performance = classification_report(
        y_true, y_pred,
        target_names=["Negative Review", "Positive Review"]
    )
    print(performance)

In [31]:
confusion_matrix(data["test"]["label"], y_pred)

array([[469,  64],
       [149, 384]])

In [32]:
from sklearn.metrics import f1_score

evaluate_performance(data["test"]["label"], y_pred)
print(f"binary F1: {f1_score(data['test']['label'], y_pred):.4f}")

                 precision    recall  f1-score   support

Negative Review       0.76      0.88      0.81       533
Positive Review       0.86      0.72      0.78       533

       accuracy                           0.80      1066
      macro avg       0.81      0.80      0.80      1066
   weighted avg       0.81      0.80      0.80      1066

binary F1: 0.7829

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

train_embeddings = model.encode(data["train"]["text"], show_progress_bar=True)
test_embeddings = model.encode(data["test"]["text"], show_progress_bar=True)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6689.32it/s]

In [ ]:
train_data, test_data = data["train"], data["test"]

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_id = "bert-base-cased"
model = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)
tokenizer = AutoTokenizer.from_pretrained(model_id)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7745.32it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import DataCollatorWithPadding


data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def preprocess_function(examples):
   return tokenizer(examples["text"], truncation=True)

tokenized_train = train_data.map(preprocess_function, batched=True)
tokenized_test = test_data.map(preprocess_function, batched=True)

In [ ]:
import numpy as np
import evaluate


def compute_metrics(eval_pred):
    """Calculate F1 score"""
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    load_f1 = evaluate.load("f1")
    f1 = load_f1.compute(predictions=predictions, references=labels)["f1"]
    return {"f1": f1}

In [ ]:
from transformers import TrainingArguments, Trainer


training_args = TrainingArguments(
   "model",
   learning_rate=2e-5,
   per_device_train_batch_size=16,
   per_device_eval_batch_size=16,
   num_train_epochs=1,
   weight_decay=0.01,
   save_strategy="epoch",
   report_to="none"
)

trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=tokenized_train,
   eval_dataset=tokenized_test,
   processing_class=tokenizer,
   data_collator=data_collator,
   compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.80it/s]

TrainOutput(global_step=534, training_loss=0.3974157844143414, metrics={'train_runtime': 68.0744, 'train_samples_per_second': 125.304, 'train_steps_per_second': 7.844, 'total_flos': 227605451772240.0, 'train_loss': 0.3974157844143414, 'epoch': 1.0})

In [ ]:
# F1 - metric 

# für praktische Anwednungen: 0.8 - 1.0 

# 10 Datenpunkte in Klasse 1
# 1000 Datenpunkte in Klasse 2 

trainer.evaluate()

/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.35696229338645935, 'eval_f1': 0.8528864059590316}

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=2
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6776.76it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
for name, param in model.named_parameters():
    print(name)

bert.embeddings.word_embeddings.weight
bert.embeddings.position_embeddings.weight
bert.embeddings.token_type_embeddings.weight
bert.embeddings.LayerNorm.weight
bert.embeddings.LayerNorm.bias
bert.encoder.layer.0.attention.self.query.weight
bert.encoder.layer.0.attention.self.query.bias
bert.encoder.layer.0.attention.self.key.weight
bert.encoder.layer.0.attention.self.key.bias
bert.encoder.layer.0.attention.self.value.weight
bert.encoder.layer.0.attention.self.value.bias
bert.encoder.layer.0.attention.output.dense.weight
bert.encoder.layer.0.attention.output.dense.bias
bert.encoder.layer.0.attention.output.LayerNorm.weight
bert.encoder.layer.0.attention.output.LayerNorm.bias
bert.encoder.layer.0.intermediate.dense.weight
bert.encoder.layer.0.intermediate.dense.bias
bert.encoder.layer.0.output.dense.weight
bert.encoder.layer.0.output.dense.bias
bert.encoder.layer.0.output.LayerNorm.weight
bert.encoder.layer.0.output.LayerNorm.bias
bert.encoder.layer.1.attention.self.query.weight
bert.encoder.layer.1.attention.self.query.bias
bert.encoder.layer.1.attention.self.key.weight
bert.encoder.layer.1.attention.self.key.bias
bert.encoder.layer.1.attention.self.value.weight
bert.encoder.layer.1.attention.self.value.bias
bert.encoder.layer.1.attention.output.dense.weight
bert.encoder.layer.1.attention.output.dense.bias
bert.encoder.layer.1.attention.output.LayerNorm.weight
bert.encoder.layer.1.attention.output.LayerNorm.bias
bert.encoder.layer.1.intermediate.dense.weight
bert.encoder.layer.1.intermediate.dense.bias
bert.encoder.layer.1.output.dense.weight
bert.encoder.layer.1.output.dense.bias
bert.encoder.layer.1.output.LayerNorm.weight
bert.encoder.layer.1.output.LayerNorm.bias
bert.encoder.layer.2.attention.self.query.weight
bert.encoder.layer.2.attention.self.query.bias
bert.encoder.layer.2.attention.self.key.weight
bert.encoder.layer.2.attention.self.key.bias
bert.encoder.layer.2.attention.self.value.weight
bert.encoder.layer.2.attention.self.value.bias
bert.encoder.layer.2.attention.output.dense.weight
bert.encoder.layer.2.attention.output.dense.bias
bert.encoder.layer.2.attention.output.LayerNorm.weight
bert.encoder.layer.2.attention.output.LayerNorm.bias
bert.encoder.layer.2.intermediate.dense.weight
bert.encoder.layer.2.intermediate.dense.bias
bert.encoder.layer.2.output.dense.weight
bert.encoder.layer.2.output.dense.bias
bert.encoder.layer.2.output.LayerNorm.weight
bert.encoder.layer.2.output.LayerNorm.bias
bert.encoder.layer.3.attention.self.query.weight
bert.encoder.layer.3.attention.self.query.bias
bert.encoder.layer.3.attention.self.key.weight
bert.encoder.layer.3.attention.self.key.bias
bert.encoder.layer.3.attention.self.value.weight
bert.encoder.layer.3.attention.self.value.bias
bert.encoder.layer.3.attention.output.dense.weight
bert.encoder.layer.3.attention.output.dense.bias
bert.encoder.layer.3.attention.output.LayerNorm.weight
bert.encoder.layer.3.attention.output.LayerNorm.bias
bert.encoder.layer.3.intermediate.dense.weight
bert.encoder.layer.3.intermediate.dense.bias
bert.encoder.layer.3.output.dense.weight
bert.encoder.layer.3.output.dense.bias
bert.encoder.layer.3.output.LayerNorm.weight
bert.encoder.layer.3.output.LayerNorm.bias
bert.encoder.layer.4.attention.self.query.weight
bert.encoder.layer.4.attention.self.query.bias
bert.encoder.layer.4.attention.self.key.weight
bert.encoder.layer.4.attention.self.key.bias
bert.encoder.layer.4.attention.self.value.weight
bert.encoder.layer.4.attention.self.value.bias
bert.encoder.layer.4.attention.output.dense.weight
bert.encoder.layer.4.attention.output.dense.bias
bert.encoder.layer.4.attention.output.LayerNorm.weight
bert.encoder.layer.4.attention.output.LayerNorm.bias
bert.encoder.layer.4.intermediate.dense.weight
bert.encoder.layer.4.intermediate.dense.bias
bert.encoder.layer.4.output.dense.weight
bert.encoder.layer.4.output.dense.bias
bert.encoder.layer.4.output.LayerNorm.weight
bert.encoder.layer.4.output.LayerNorm.bias
bert.encoder.layer.5.attention.self.query.weight
bert.encoder.layer.5.attention.self.query.bias
bert.encoder.layer.5.attention.self.key.weight
bert.encoder.layer.5.attention.self.key.bias
bert.encoder.layer.5.attention.self.value.weight
bert.encoder.layer.5.attention.self.value.bias
bert.encoder.layer.5.attention.output.dense.weight
bert.encoder.layer.5.attention.output.dense.bias
bert.encoder.layer.5.attention.output.LayerNorm.weight
bert.encoder.layer.5.attention.output.LayerNorm.bias
bert.encoder.layer.5.intermediate.dense.weight
bert.encoder.layer.5.intermediate.dense.bias
bert.encoder.layer.5.output.dense.weight
bert.encoder.layer.5.output.dense.bias
bert.encoder.layer.5.output.LayerNorm.weight
bert.encoder.layer.5.output.LayerNorm.bias
bert.encoder.layer.6.attention.self.query.weight
bert.encoder.layer.6.attention.self.query.bias
bert.encoder.layer.6.attention.self.key.weight
bert.encoder.layer.6.attention.self.key.bias
bert.encoder.layer.6.attention.self.value.weight
bert.encoder.layer.6.attention.self.value.bias
bert.encoder.layer.6.attention.output.dense.weight
bert.encoder.layer.6.attention.output.dense.bias
bert.encoder.layer.6.attention.output.LayerNorm.weight
bert.encoder.layer.6.attention.output.LayerNorm.bias
bert.encoder.layer.6.intermediate.dense.weight
bert.encoder.layer.6.intermediate.dense.bias
bert.encoder.layer.6.output.dense.weight
bert.encoder.layer.6.output.dense.bias
bert.encoder.layer.6.output.LayerNorm.weight
bert.encoder.layer.6.output.LayerNorm.bias
bert.encoder.layer.7.attention.self.query.weight
bert.encoder.layer.7.attention.self.query.bias
bert.encoder.layer.7.attention.self.key.weight
bert.encoder.layer.7.attention.self.key.bias
bert.encoder.layer.7.attention.self.value.weight
bert.encoder.layer.7.attention.self.value.bias
bert.encoder.layer.7.attention.output.dense.weight
bert.encoder.layer.7.attention.output.dense.bias
bert.encoder.layer.7.attention.output.LayerNorm.weight
bert.encoder.layer.7.attention.output.LayerNorm.bias
bert.encoder.layer.7.intermediate.dense.weight
bert.encoder.layer.7.intermediate.dense.bias
bert.encoder.layer.7.output.dense.weight
bert.encoder.layer.7.output.dense.bias
bert.encoder.layer.7.output.LayerNorm.weight
bert.encoder.layer.7.output.LayerNorm.bias
bert.encoder.layer.8.attention.self.query.weight
bert.encoder.layer.8.attention.self.query.bias
bert.encoder.layer.8.attention.self.key.weight
bert.encoder.layer.8.attention.self.key.bias
bert.encoder.layer.8.attention.self.value.weight
bert.encoder.layer.8.attention.self.value.bias
bert.encoder.layer.8.attention.output.dense.weight
bert.encoder.layer.8.attention.output.dense.bias
bert.encoder.layer.8.attention.output.LayerNorm.weight
bert.encoder.layer.8.attention.output.LayerNorm.bias
bert.encoder.layer.8.intermediate.dense.weight
bert.encoder.layer.8.intermediate.dense.bias
bert.encoder.layer.8.output.dense.weight
bert.encoder.layer.8.output.dense.bias
bert.encoder.layer.8.output.LayerNorm.weight
bert.encoder.layer.8.output.LayerNorm.bias
bert.encoder.layer.9.attention.self.query.weight
bert.encoder.layer.9.attention.self.query.bias
bert.encoder.layer.9.attention.self.key.weight
bert.encoder.layer.9.attention.self.key.bias
bert.encoder.layer.9.attention.self.value.weight
bert.encoder.layer.9.attention.self.value.bias
bert.encoder.layer.9.attention.output.dense.weight
bert.encoder.layer.9.attention.output.dense.bias
bert.encoder.layer.9.attention.output.LayerNorm.weight
bert.encoder.layer.9.attention.output.LayerNorm.bias
bert.encoder.layer.9.intermediate.dense.weight
bert.encoder.layer.9.intermediate.dense.bias
bert.encoder.layer.9.output.dense.weight
bert.encoder.layer.9.output.dense.bias
bert.encoder.layer.9.output.LayerNorm.weight
bert.encoder.layer.9.output.LayerNorm.bias
bert.encoder.layer.10.attention.self.query.weight
bert.encoder.layer.10.attention.self.query.bias
bert.encoder.layer.10.attention.self.key.weight
bert.encoder.layer.10.attention.self.key.bias
bert.encoder.layer.10.attention.self.value.weight
bert.encoder.layer.10.attention.self.value.bias
bert.encoder.layer.10.attention.output.dense.weight
bert.encoder.layer.10.attention.output.dense.bias
bert.encoder.layer.10.attention.output.LayerNorm.weight
bert.encoder.layer.10.attention.output.LayerNorm.bias
bert.encoder.layer.10.intermediate.dense.weight
bert.encoder.layer.10.intermediate.dense.bias
bert.encoder.layer.10.output.dense.weight
bert.encoder.layer.10.output.dense.bias
bert.encoder.layer.10.output.LayerNorm.weight
bert.encoder.layer.10.output.LayerNorm.bias
bert.encoder.layer.11.attention.self.query.weight
bert.encoder.layer.11.attention.self.query.bias
bert.encoder.layer.11.attention.self.key.weight
bert.encoder.layer.11.attention.self.key.bias
bert.encoder.layer.11.attention.self.value.weight
bert.encoder.layer.11.attention.self.value.bias
bert.encoder.layer.11.attention.output.dense.weight
bert.encoder.layer.11.attention.output.dense.bias
bert.encoder.layer.11.attention.output.LayerNorm.weight
bert.encoder.layer.11.attention.output.LayerNorm.bias
bert.encoder.layer.11.intermediate.dense.weight
bert.encoder.layer.11.intermediate.dense.bias
bert.encoder.layer.11.output.dense.weight
bert.encoder.layer.11.output.dense.bias
bert.encoder.layer.11.output.LayerNorm.weight
bert.encoder.layer.11.output.LayerNorm.bias
bert.pooler.dense.weight
bert.pooler.dense.bias
classifier.weight
classifier.bias

In [ ]:
for name, param in model.named_parameters():
     # Trainable classification head
     if name.startswith("classifier"):
        param.requires_grad = True
      # Freeze everything else
     else:
        param.requires_grad = False

In [ ]:
from transformers import TrainingArguments, Trainer

# Trainer which executes the training process
trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=tokenized_train,
   eval_dataset=tokenized_test,
   processing_class=tokenizer,
   data_collator=data_collator,
   compute_metrics=compute_metrics,
)
trainer.train()

/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

TrainOutput(global_step=534, training_loss=0.6943903505132439, metrics={'train_runtime': 18.0647, 'train_samples_per_second': 472.191, 'train_steps_per_second': 29.56, 'total_flos': 227605451772240.0, 'train_loss': 0.6943903505132439, 'epoch': 1.0})

In [ ]:
# 0.6 - mittelmäßige Performance s

trainer.evaluate()

/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.6818975806236267, 'eval_f1': 0.6308724832214765}

In [ ]:
# Load model
model_id = "bert-base-cased"
model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=2
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Encoder block 11 starts at index 165 and
# we freeze everything before that block
for index, (name, param) in enumerate(model.named_parameters()):
    if index < 165:
        param.requires_grad = False

# Trainer which executes the training process
trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=tokenized_train,
   eval_dataset=tokenized_test,
   processing_class=tokenizer,
   data_collator=data_collator,
   compute_metrics=compute_metrics,
)
trainer.train()

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 18896.68it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.18it/s]

TrainOutput(global_step=534, training_loss=0.4722876709498716, metrics={'train_runtime': 23.9274, 'train_samples_per_second': 356.495, 'train_steps_per_second': 22.318, 'total_flos': 227605451772240.0, 'train_loss': 0.4722876709498716, 'epoch': 1.0})

In [ ]:
trainer.evaluate()

/Users/grigo/gits/seminars/it-schulungen.com/Siemens/ML Basics/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.41169705986976624, 'eval_f1': 0.8164435946462715}

In [ ]:
(len(list(model.named_parameters())) - 165) / len(list(model.named_parameters()))

0.1791044776119403